export const SET_PDF_FILES = "SET_PDF_FILES"
export const SET_EXTRACTED_DATA = "SET_EXTRACTED_DATA"
export const SET_DATA_TABLE_HEADERS = "SET_DATA_TABLE_HEADERS"
export const SWITCH_LOADER_STATE = "SWITCH_LOADER_STATE"